
# faster builds on new travis setup not using sudo
sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - |
    if [[ $TRAVIS_PHP_VERSION != '7.1' && $TRAVIS_PHP_VERSION != hhv* ]]; then
        # disable xdebug for performance reasons when code coverage is not needed
        # note: xdebug on hhvm is disabled by default
        phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version
            
  # initialize database
  - mysql -e "create database yii2_workflow_test"

  # enable code coverage on PHP 7.1, only one PHP version needs to generate coverage data
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      CODECEPTION_FLAGS="--coverage-xml"
    fi

script:
  - composer deploy-tests
  - composer run-tests

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
    fi
